# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getUpAndInCallPrice <- function(InitialPriceOfAsset, StrikePrice, Volatility, InterestRate, TimeToMaturity, BarrierLevel, numSimulations, numTimeSteps) {
    .Call(`_OptionMonteCarlo_getUpAndInCallPrice`, InitialPriceOfAsset, StrikePrice, Volatility, InterestRate, TimeToMaturity, BarrierLevel, numSimulations, numTimeSteps)
}

